# Generated by Django 4.2.1 on 2023-05-31 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Albuns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='shared_with',
            field=models.ManyToManyField(related_name='album_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com'),
        ),
    ]
