# Generated by Django 4.2.1 on 2023-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='primeiro_login',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='Media/no_image_dafaut.jpg', null=True, upload_to='Media'),
        ),
    ]
