# Generated by Django 4.2.1 on 2023-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_customuser_primeiro_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primeiro_login',
            field=models.DateField(auto_now_add=True, default=None, verbose_name='Quando a conta foi criada'),
            preserve_default=False,
        ),
    ]
