# Generated by Django 4.2.1 on 2023-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('discription', models.CharField(max_length=500, verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to=None, verbose_name='Foto')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Ultima Alteração')),
            ],
        ),
    ]
