# Generated by Django 4.2.1 on 2023-05-31 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Albuns', '0001_initial'),
        ('Photos', '0003_alter_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Albuns.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='photo_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com'),
        ),
    ]
