# Generated by Django 4.2.1 on 2023-05-31 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Albuns', '0002_alter_album_shared_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Photos', '0004_photo_album_alter_photo_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Albuns.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shared_with',
            field=models.ManyToManyField(related_name='photo_shared_with', to=settings.AUTH_USER_MODEL, verbose_name='Compartilhado com'),
        ),
    ]
